steps:
  # Access the secret and write it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=gsheets-credentials > src/config/google-credentials.json
        
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/resume-454421/stack-site', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/resume-454421/stack-site']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'stack-site'
    - '--image'
    - 'gcr.io/resume-454421/stack-site'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS=gsheets-credentials:latest'

images:
  - 'gcr.io/resume-454421/stack-site'